# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 028ad5b42e4050731e098223a4c82410c159105e1463674dc7b7ec96363e5d8534ff102e23c1135dabfb45d5786a5f1ecde433e37c6fcc2557591474c339299c

test:
  secret_key_base: 6ee805ea0b6249745822149317132cab48cbab54916aba60bb5d9fee43bfa3d5b452dac23e380b6120cce05f103fdfa48c4ca090f39febb55fa22b7ff975d2cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
